baseURL = 'https://amarjandu.github.io/'
languageCode = 'en-us'
title = 'amar'
theme = 'cactus'

[[params.social]]
name = "github"
link = "https://github.com/amarjandu"

[[params.social]]
name = "linkedin"
link = "https://linkedin.com/in/amarjandu"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4